name: Test Runner

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Self-hosted runner is working!"
